services:
  cafloma-application: 
    container_name: cafloma-application
    build: 
      context: ./cafloma
      dockerfile: Dockerfile
    environment:
      - BOOT_PROFILE_GROUP=${BOOT_PROFILE_GROUP}
      - PORT=${PORT}
      - DB_NAME=jdbc:postgresql://cafloma-database:${DB_PORT}/postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - cafloma-database
  cafloma-database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=jdbc:postgresql://cafloma-database:${DB_PORT}/postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
