services:
  cafloma-application:
    networks:
      - public
      - private
    container_name: cafloma-application
    build: 
      context: ./cafloma
      dockerfile: Dockerfile
    environment:
      - BOOT_PROFILE_GROUP=${BOOT_PROFILE_GROUP}
      - APP_PORT=${APP_PORT}
      - DB_NAME=jdbc:postgresql://cafloma-database:5432/postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - cafloma-database
  cafloma-database:
    networks:
      - private
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

networks:
  public:
    driver: bridge
  private:
    driver: bridge
