
# Contains all profiles which settings should be active in local
spring.profiles.group.local = base-local

# Contains all profiles which settings should be active in prd
spring.profiles.group.prd = base-prd