services:
  cafloma-application:
    networks:
      - public
      - private
    container_name: cafloma-application
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - BOOT_PROFILE_GROUP=${BOOT_PROFILE_GROUP}
      - APP_PORT=${APP_PORT}
      - DB_URL=jdbc:postgresql://cafloma-database:${DB_PORT}/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - cafloma-database
  cafloma-database:
    networks:
      - private
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
